name: Application Monitoring

# Temporarily disabled until health check endpoints are ready
# on:
#   schedule:
#     - cron: '*/15 * * * *'  # Run every 15 minutes

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Check repository
        run: echo "Monitoring temporarily disabled until health check endpoints are configured."