name: Application Monitoring

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes

jobs:
  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Check API health
        uses: jtalk/url-health-check-action@v3
        with:
          url: ${{ secrets.API_HEALTH_CHECK_URL }}
          max-attempts: 3
          retry-delay: 5s